<?php

/**
 * Schedule export template
 *
 * @link       http://example.com
 * @since      1.2.0
 *
 * @package    Export_For_MemberPress
 * @subpackage Export_For_MemberPress/admin/partials
 */


$reports = Export_For_MemberPress_Admin::get_history_reports();
?>

<header class="defm-tab-header">
    <h1 class="defm-tab-panel-title"><?php _e('History of Generated Reports', 'export-for-memberpress'); ?></h1>
    <div class="defm-filter-history">
        <label for="defm_filter_type"><?php _e('Filter', 'export-for-memberpress'); ?>:</label>
        <select id="defm_filter_type" name="defm_filter_type">
            <option value=".defm-report"><?php _e('All reports', 'export-for-memberpress'); ?></option>
            <option value=".defm-manual-report"><?php _e('Manual reports', 'export-for-memberpress'); ?></option>
            <option value=".defm-group-report"><?php _e('Group reports', 'export-for-memberpress'); ?></option>
            <option value=".defm-auto-report"><?php _e('Generated by scheduled reports', 'export-for-memberpress'); ?></option>
        </select>
        <span id="defm_generated_by_filter" class="defm-generated-by-filter">
            <?php Export_For_MemberPress_Admin::generated_by_options('defm_filter_generated_by'); ?>
        </span>
        <button id="defm_history_delete" class="button button-primary defm-button defm-delete dashicons-before dashicons-trash">
            <span class="defm-button-label"><?php _e('Delete All', 'export-for-memberpress'); ?></span>
        </button>
    </div>
</header>

<section class="defm-tab-panel-content-section">
    <ul id="defm_history_reports">
        <?php if ($reports) :

                foreach ($reports as $report) {
                     include plugin_dir_path( __FILE__ ) . 'single-history-report.php';
                 }

             else : ?>
            <li id="defm_no_history_reports"><?php _e('No reports generated yet.', 'export-for-memberpress'); ?></li>
        <?php endif; ?>
    </ul>
</section>

<?php
